### ISSUE TITLE
Cannot create Techpoint user in Accounts

### ISSUE THREAD

**Issue by crowleaj** [Xtern-Matching/Xtern-Matching#69]

**Comment by crowleaj** [comment]
orgKey parameter needs to be Techpoint's key, not "Techpoint"

**Comment by davisnygren** [comment]
This issue also exists for creating an Instructor user - gives a 500 error: unexpected EOF

**Comment by davisnygren** [comment]
This should be fixed in the front end since the controller already has the DB keys
![image](https://cloud.githubusercontent.com/assets/10641685/21827557/2af94f0e-d75a-11e6-8eb7-c7743ae1f363.png)
